name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Check out code
        uses: actions/checkout@v1
      - name: cache go mod
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: Build
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0
          export PATH=$PATH:$(go env GOPATH)/bin
          make check
          make build
      - name: test
        run: |
          export NYDUS_VERSION=v2.1.0-rc.2
          curl -L https://github.com/dragonflyoss/image-service/releases/download/$NYDUS_VERSION/nydus-static-$NYDUS_VERSION-linux-amd64.tgz > nydus-static-$NYDUS_VERSION-linux-amd64.tgz
          tar xzvf nydus-static-$NYDUS_VERSION-linux-amd64.tgz
          mv nydus-static/nydusd-fusedev /usr/bin/nydusd
          mv nydus-static/nydusify /usr/bin/nydusify
          mv nydus-static/nydus-image /usr/bin/nydus-image
          apt-get -y update
          apt-get -y install podman
          mkdir -p /var/lib/nydus-store
          cp nydus-config.json /etc/nydusd-config.json
          cp storage.conf /etc/containers/storage.conf
          nohup bin/nydus-store &
          podman run -d ghcr.io/dragonflyoss/image-service/nginx:nydus-latest
